Feature/no maap cfg
MAAP-Project/maap-workspaces pull request #120
Opened 2024-06-24 18:54 UTC by grallewellyn

This PR merged in Sujen's changes to remove the need to track maap.cfg file

We will need to deploy the changes to the devfiles when we merge this PR so that the `MAAP_API_HOST` variable is present. `MAAP_API_HOST` points to the ops api by default so it will need to be added to the devfiles for dit and uat

2024-06-26 21:29 UTC, sujen1412 requested changes

2024-06-26 21:29 UTC, sujen1412 commented on devfiles/isce3/devfile/devfile.yaml
> +                  value: https://ade.dit.maap-project.org/api
This value should be `ade.dit.maap-project.org`

2024-06-26 21:29 UTC, sujen1412 commented on devfiles/pangeo/devfile/devfile.yaml
> +                  value: https://ade.dit.maap-project.org/api
This value should be `ade.dit.maap-project.org`

2024-06-26 21:29 UTC, sujen1412 commented on devfiles/python/devfile/devfile.yaml
> +                  value: https://ade.dit.maap-project.org/api
This value should be `ade.dit.maap-project.org`

2024-06-26 21:29 UTC, sujen1412 commented on devfiles/r/devfile/devfile.yaml
> +                  value: https://ade.dit.maap-project.org/api
This value should be `ade.dit.maap-project.org`

2024-06-26 21:47 UTC, sujen1412 submitted a review, later dismissed

2024-06-26 22:08 UTC, sujen1412 approved these changes

2024-06-26 22:45 UTC, merged

2024-06-28 19:08 UTC, sujen1412 commented
I just realized that I did not read the env value correctly. The API host is supposed to point to api.*.maap-project.org and not ade.*.maap-project.org. Sorry missed this.

2024-07-04 06:59 UTC, grallewellyn commented
@sujen1412 Created a PR to address this here: https://github.com/MAAP-Project/maap-workspaces/pull/126